# Generated by Django 4.1.5 on 2023-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_updated_at_alter_coupon_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='catgories'),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='size_name',
            field=models.CharField(max_length=100),
        ),
    ]
